### ISSUE TITLE
Fbot 2 errors, no nodes shut off

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/farmerbot#57] opened 2023-07-26 23:30 UTC
From farmer:

"
My first attempt had the farmerbot working for a day, then it stopped.  I redid the farmerbot and now nothing shuts off.  Ideas?
"

Link to log file: https://t.me/threefoldtesting/13370

Errors:  

The two main kind of errors I see are:

1. 2023-07-24 01:14:35 [ERROR] [DATAMANAGER] Node 126 is not responding while we expect it to.

2. 2023-07-24 01:59:35 [INFO ] [DATAMANAGER] Node 53 is waking up.9382023-07-24 01:59:35 [ERROR] [DATAMANAGER] Node 151 wakeup was unsuccessful. Putting its state back to off.

@brandonpille any ideas? Thanks

From @brandonpille, the nodes with ids 151, 53, 4198, 126 can't be contacted via rmb and therefore the farmerbot is not able to notice they are still online. The node 26 can though (which is the node that is marked as never_shutdown). In the logs I see a successful attempt for waking up 151 after the farmer rebooted manually. But after one day it fails to do periodic wakeup (meaning the node does not answer the rmb calls anymore).

**Comment by Nelson361** [comment] 2023-07-27 00:28
All nodes are currently powered on.  They are not "waking up" as the logs indicate.

**Comment by brandonpille** [comment] 2023-07-27 06:58
It looks like the nodes are not responding to the rmb messages from the farmerbot, thus it thinks they are offline. Can I get all the logs: docker compose logs?

**Comment by brandonpille** [comment] 2023-07-27 07:20
Also do you have the logs from the first run?

**Comment by brandonpille** [comment] 2023-07-27 07:33
The log file shows me the logs from two different farmerbot runs. How many times did you run it? If only twice the first farmerbot run also shows me that it could not contact any of the nodes except for node 26. I tried contacting the nodes myself (with my rmb-peer), no succes either. So there must be something with the rmb running on your nodes. I recommend manually rebooting those nodes.

**Comment by brandonpille** [comment] 2023-07-27 09:32
After a talk with Azmy we noticed that there might be a rmb bug: the recv queue of the rmb connection is full due to the rmb peer not being able to read the data (issue https://github.com/threefoldtech/rmb-rs/issues/143). Once the issue is fixed the farmerbot will be able to contact the nodes and properly do its thing.

**Comment by Nelson361** [comment] 2023-07-27 10:05
I've ran farmerbot a couple times, but I did it rebuild the linux distro between runs, so I don't know how an old one could be logged.  Node 53 did respond last night. 
[farmerbot.log](https://github.com/threefoldtech/farmerbot/files/12182036/farmerbot.log)

**Comment by brandonpille** [comment] 2023-07-28 08:00
Yes Azmy killed the rmb peer and restarted it so that's why. We have a bug fix running on devnet right now. Once we are confident we can deploy and I'll have to release a new farmerbot.

**Comment by brandonpille** [comment] 2023-08-17 09:55
I read the issue #61 which tells me the issue is still there. That is normal as the fix is not yet on mainnet. But a reboot should have fixed the issue which means the issue is presenting itself very frequently. @Nelson361 can you confirm you rebooted recently? Can you also tell us exactly what you did to the nodes (if you did something)?

@muhamadazmy can you check the nodes and see if it's still the same issue?

**Comment by Nelson361** [comment] 2023-08-17 12:28
I've done a lot of switching on and off. They do well at being turned on by the farmer bot when they are manually shut off, but they never go to sleep.  If there's any steps I can do to help you troubleshoot let me know, or we can wait until the update.

**Comment by muhamadazmy** [comment] 2023-08-18 09:09
There was an issue with rmb agent on the node on production, the issue has been fixed on qa and devnet. 

Although the issue appears with you a lot it's really hard to reproduce and the only information of it is by inspecting the state of already affected nodes (which is not easy since accessing the nodes is impossible in remote farms). 

The potential fix is available, BUT the only way to push that to mainnet now is either by patching, or waiting for the next release. I will see which one is more feasible and get back to you

**Comment by scottyeager** [comment] 2023-08-28 19:20
Hi @muhamadazmy, any update on this one? Would be great if we could deploy this fix as a patch asap.

**Comment by muhamadazmy** [comment] 2023-08-29 13:58
@scottyeager the rmb patch is included in the next grid release unfortunately I can't rush deployment of the zos update. There is also a fix in power management on the node (related to https://github.com/threefoldtech/zos/issues/2029) but this unfortunately won't be included in the next release yet

**Closed as completed** 2024-08-01 13:19 UTC
