### ISSUE TITLE
Failed to get next event + redis.sock : no such file or directory

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/farmerbot#40] opened 2023-05-21 14:25 UTC
A TF Farmer had error messages on his zero-os screen after setting the farmerbot.

Here is the main screen. error/log screen should follow soon.

![tf_farmer_error_redis_farmerbot](https://github.com/threefoldtech/farmerbot/assets/77026219/5fe1d537-2fa5-4735-9172-078c322a172e)

[source](https://t.me/threefoldfarmers/61022)

**Comment by scottyeager** [comment] 2023-05-22 16:57
Duplicate of https://github.com/threefoldtech/zos/issues/1968

Potentially good intel that this happened after setting up the farmerbot. I'll add the info to the existing issue.

**Closed as not planned** 2023-05-22 17:25 UTC
